# Generated by Django 5.0.6 on 2024-08-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[(0, 'Live'), (1, 'Delete')], default=0),
        ),
    ]
